language: go

sudo: required

go:
  - 1.10.x

env:
  global:
    - OPERATOR_NAME=gitea-operator

stages:
  - test
  - compile

jobs:
  include:
    - stage: test
      script:
        - make setup/dep setup/travis code/check test/unit
    - stage: compile
      script:
        - make setup/dep setup/travis image/build TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
